#!/bin/zsh

export DOTFILES="$HOME/.files"
export ZHOME="$DOTFILES/10-shell.d"
export ZCONF="$ZHOME/config"

export GPG_TTY=$(tty)

# all of our zsh files
typeset -U config_files
config_files=($DOTFILES/**/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}; do
  source "$file"
done

# load the env files
for file in ${(M)config_files:#*/env.zsh}; do
  source "$file"
done

# load theme configuration
source "$ZCONF"/prompt.zsh

# load antibody plugins
source $DCACHE/zsh_plugins_static.zsh

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  source "$file"
done

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}; do
  source "$file"
done

unset config_files updated_at
